"""
Populate D&D 5e feats database
"""

from django.core.management.base import BaseCommand
from characters.models import Feat


class Command(BaseCommand):
    help = 'Populate D&D 5e feats database'

    def handle(self, *args, **options):
        feats = [
            {
                'name': 'Great Weapon Master',
                'description': 'You\'ve learned to put the weight of a weapon to your advantage, letting its momentum empower your strikes. You gain the following benefits: On your turn, when you score a critical hit with a melee weapon or reduce a creature to 0 hit points with one, you can make one melee weapon attack as a bonus action. Before you make a melee attack with a heavy weapon that you are proficient with, you can choose to take a -5 penalty to the attack roll. If the attack hits, you add +10 to the attack\'s damage.',
                'strength_requirement': 0,
                'dexterity_requirement': 0,
                'constitution_requirement': 0,
                'intelligence_requirement': 0,
                'wisdom_requirement': 0,
                'charisma_requirement': 0,
                'minimum_level': 4,
                'proficiency_requirements': 'Martial Weapons',
            },
            {
                'name': 'Sharpshooter',
                'description': 'You have mastered ranged weapons and can make shots that others find impossible. You gain the following benefits: Attacking at long range doesn\'t impose disadvantage on your ranged weapon attack rolls. Your ranged weapon attacks ignore half cover and three-quarters cover. Before you make an attack with a ranged weapon that you are proficient with, you can choose to take a -5 penalty to the attack roll. If the attack hits, you add +10 to the attack\'s damage.',
                'strength_requirement': 0,
                'dexterity_requirement': 0,
                'constitution_requirement': 0,
                'intelligence_requirement': 0,
                'wisdom_requirement': 0,
                'charisma_requirement': 0,
                'minimum_level': 4,
                'proficiency_requirements': '',
            },
            {
                'name': 'War Caster',
                'description': 'You have practiced casting spells in the midst of combat, learning techniques that grant you the following benefits: You have advantage on Constitution saving throws that you make to maintain your concentration on a spell when you take damage. You can perform the somatic components of spells even when you have weapons or a shield in one or both hands. When a hostile creature\'s movement provokes an opportunity attack from you, you can use your reaction to cast a spell at the creature, rather than making an opportunity attack. The spell must have a casting time of 1 action and must target only that creature.',
                'strength_requirement': 0,
                'dexterity_requirement': 0,
                'constitution_requirement': 0,
                'intelligence_requirement': 0,
                'wisdom_requirement': 0,
                'charisma_requirement': 0,
                'minimum_level': 4,
                'proficiency_requirements': '',
            },
            {
                'name': 'Lucky',
                'description': 'You have inexplicable luck that seems to kick in at just the right moment. You have 3 luck points. Whenever you make an attack roll, an ability check, or a saving throw, you can spend one luck point to roll an additional d20. You can choose to spend one of your luck points after you roll the die, but before the outcome is determined. You choose which of the d20s is used for the attack roll, ability check, or saving throw. You can also spend one luck point when an attack roll is made against you. Roll a d20, and then choose whether the attack uses the attacker\'s roll or yours. If more than one creature spends a luck point to influence the outcome of a roll, the points cancel each other out; no additional dice are rolled. You regain your expended luck points when you finish a long rest.',
                'strength_requirement': 0,
                'dexterity_requirement': 0,
                'constitution_requirement': 0,
                'intelligence_requirement': 0,
                'wisdom_requirement': 0,
                'charisma_requirement': 0,
                'minimum_level': 4,
                'proficiency_requirements': '',
            },
            {
                'name': 'Alert',
                'description': 'Always on the lookout for danger, you gain the following benefits: You gain a +5 bonus to initiative. You can\'t be surprised while you are conscious. Other creatures don\'t gain advantage on attack rolls against you as a result of being hidden from you.',
                'strength_requirement': 0,
                'dexterity_requirement': 0,
                'constitution_requirement': 0,
                'intelligence_requirement': 0,
                'wisdom_requirement': 0,
                'charisma_requirement': 0,
                'minimum_level': 4,
                'proficiency_requirements': '',
            },
            {
                'name': 'Resilient',
                'description': 'Choose one ability score. You gain proficiency in saving throws using the chosen ability.',
                'strength_requirement': 0,
                'dexterity_requirement': 0,
                'constitution_requirement': 0,
                'intelligence_requirement': 0,
                'wisdom_requirement': 0,
                'charisma_requirement': 0,
                'minimum_level': 4,
                'proficiency_requirements': '',
            },
            {
                'name': 'Tough',
                'description': 'Your hit point maximum increases by an amount equal to twice your level when you gain this feat. Whenever you gain a level thereafter, your hit point maximum increases by an additional 2 hit points.',
                'strength_requirement': 0,
                'dexterity_requirement': 0,
                'constitution_requirement': 0,
                'intelligence_requirement': 0,
                'wisdom_requirement': 0,
                'charisma_requirement': 0,
                'minimum_level': 4,
                'proficiency_requirements': '',
            },
            {
                'name': 'Mobile',
                'description': 'You are exceptionally speedy and agile. You gain the following benefits: Your speed increases by 10 feet. When you use the Dash action, difficult terrain doesn\'t cost you extra movement on that turn. When you make a melee attack against a creature, you don\'t provoke opportunity attacks from that creature for the rest of the turn, whether you hit or not.',
                'strength_requirement': 0,
                'dexterity_requirement': 0,
                'constitution_requirement': 0,
                'intelligence_requirement': 0,
                'wisdom_requirement': 0,
                'charisma_requirement': 0,
                'minimum_level': 4,
                'proficiency_requirements': '',
            },
            {
                'name': 'Sentinel',
                'description': 'You have mastered techniques to take advantage of every drop in any enemy\'s guard, gaining the following benefits: When you hit a creature with an opportunity attack, the creature\'s speed becomes 0 for the rest of the turn. Creatures within 5 feet of you provoke opportunity attacks from you even if they take the Disengage action before leaving your reach. When a creature within 5 feet of you makes an attack against a target other than you (and that target doesn\'t have this feat), you can use your reaction to make a melee weapon attack against the attacking creature.',
                'strength_requirement': 0,
                'dexterity_requirement': 0,
                'constitution_requirement': 0,
                'intelligence_requirement': 0,
                'wisdom_requirement': 0,
                'charisma_requirement': 0,
                'minimum_level': 4,
                'proficiency_requirements': '',
            },
            {
                'name': 'Polearm Master',
                'description': 'You can keep your enemies at bay with reach weapons. You gain the following benefits: When you take the Attack action and attack with only a glaive, halberd, quarterstaff, or spear, you can use a bonus action to make a melee attack with the opposite end of the weapon. This attack uses the same ability modifier as the primary attack. The weapon\'s damage die for this attack is a d4, and it deals bludgeoning damage. While you are wielding a glaive, halberd, pike, quarterstaff, or spear, other creatures provoke an opportunity attack from you when they enter your reach.',
                'strength_requirement': 0,
                'dexterity_requirement': 0,
                'constitution_requirement': 0,
                'intelligence_requirement': 0,
                'wisdom_requirement': 0,
                'charisma_requirement': 0,
                'minimum_level': 4,
                'proficiency_requirements': '',
            },
            {
                'name': 'Crossbow Expert',
                'description': 'Thanks to extensive practice with the crossbow, you gain the following benefits: You ignore the loading property of crossbows with which you are proficient. Being within 5 feet of a hostile creature doesn\'t impose disadvantage on your ranged attack rolls. When you use the Attack action and attack with a one-handed weapon, you can use a bonus action to attack with a hand crossbow you are holding.',
                'strength_requirement': 0,
                'dexterity_requirement': 0,
                'constitution_requirement': 0,
                'intelligence_requirement': 0,
                'wisdom_requirement': 0,
                'charisma_requirement': 0,
                'minimum_level': 4,
                'proficiency_requirements': '',
            },
            {
                'name': 'Dual Wielder',
                'description': 'You master fighting with two weapons, gaining the following benefits: You gain a +1 bonus to AC while you are wielding a separate melee weapon in each hand. You can use two-weapon fighting even when the one-handed melee weapons you are wielding aren\'t light. You can draw or stow two one-handed weapons when you would normally be able to draw or stow only one.',
                'strength_requirement': 0,
                'dexterity_requirement': 0,
                'constitution_requirement': 0,
                'intelligence_requirement': 0,
                'wisdom_requirement': 0,
                'charisma_requirement': 0,
                'minimum_level': 4,
                'proficiency_requirements': '',
            },
            {
                'name': 'Mage Slayer',
                'description': 'You have practiced techniques useful in melee combat against spellcasters, gaining the following benefits: When a creature within 5 feet of you casts a spell, you can use your reaction to make a melee weapon attack against that creature. When you damage a creature that is concentrating on a spell, that creature has disadvantage on the saving throw it makes to maintain its concentration. You have advantage on saving throws against spells cast by creatures within 5 feet of you.',
                'strength_requirement': 0,
                'dexterity_requirement': 0,
                'constitution_requirement': 0,
                'intelligence_requirement': 0,
                'wisdom_requirement': 0,
                'charisma_requirement': 0,
                'minimum_level': 4,
                'proficiency_requirements': '',
            },
            {
                'name': 'Magic Initiate',
                'description': 'Choose a class: bard, cleric, druid, sorcerer, warlock, or wizard. You learn two cantrips of your choice from that class\'s spell list. In addition, choose one 1st-level spell from that same list. You learn that spell and can cast it at its lowest level. Once you cast it, you must finish a long rest before you can cast it again using this feat. Your spellcasting ability for these spells depends on the class you chose: Charisma for bard, sorcerer, or warlock; Wisdom for cleric or druid; or Intelligence for wizard.',
                'strength_requirement': 0,
                'dexterity_requirement': 0,
                'constitution_requirement': 0,
                'intelligence_requirement': 0,
                'wisdom_requirement': 0,
                'charisma_requirement': 0,
                'minimum_level': 4,
                'proficiency_requirements': '',
            },
            {
                'name': 'Observant',
                'description': 'Quick to notice details of your environment, you gain the following benefits: If you can see a creature\'s mouth while it is speaking a language you understand, you can interpret what it\'s saying by reading its lips. You have a +5 bonus to your passive Wisdom (Perception) and passive Intelligence (Investigation) scores.',
                'strength_requirement': 0,
                'dexterity_requirement': 0,
                'constitution_requirement': 0,
                'intelligence_requirement': 13,
                'wisdom_requirement': 13,
                'charisma_requirement': 0,
                'minimum_level': 4,
                'proficiency_requirements': '',
            },
            {
                'name': 'Actor',
                'description': 'Skilled at mimicry and dramatics, you gain the following benefits: You have advantage on Charisma (Deception) and Charisma (Performance) checks when trying to pass yourself off as a different person. You can mimic the speech of another person or the sounds made by other creatures. You must have heard the person speaking, or heard the creature make the sound, for at least 1 minute. A successful Wisdom (Insight) check contested by your Charisma (Deception) check allows a listener to determine that the effect is faked.',
                'strength_requirement': 0,
                'dexterity_requirement': 0,
                'constitution_requirement': 0,
                'intelligence_requirement': 0,
                'wisdom_requirement': 0,
                'charisma_requirement': 13,
                'minimum_level': 4,
                'proficiency_requirements': '',
                'ability_score_increase': 'CHA',
            },
            {
                'name': 'Athlete',
                'description': 'You have undergone extensive physical training to gain the following benefits: When you are prone, standing up uses only 5 feet of your movement. Climbing doesn\'t cost you extra movement. You can make a running long jump or a running high jump after moving only 5 feet on foot, rather than 10 feet.',
                'strength_requirement': 0,
                'dexterity_requirement': 0,
                'constitution_requirement': 0,
                'intelligence_requirement': 0,
                'wisdom_requirement': 0,
                'charisma_requirement': 0,
                'minimum_level': 4,
                'proficiency_requirements': '',
                'ability_score_increase': 'STR',
            },
            {
                'name': 'Durable',
                'description': 'Hardy and resilient, you gain the following benefits: Increase your Constitution score by 1, to a maximum of 20. When you roll a Hit Die to regain hit points, the minimum number of hit points you regain from the roll equals twice your Constitution modifier (minimum of 2).',
                'strength_requirement': 0,
                'dexterity_requirement': 0,
                'constitution_requirement': 0,
                'intelligence_requirement': 0,
                'wisdom_requirement': 0,
                'charisma_requirement': 0,
                'minimum_level': 4,
                'proficiency_requirements': '',
                'ability_score_increase': 'CON',
            },
            {
                'name': 'Grappler',
                'description': 'You\'ve developed the skills necessary to hold your own in close-quarters grappling. You gain the following benefits: You have advantage on attack rolls against a creature you are grappling. You can use your action to try to pin a creature grappled by you. To do so, make another grapple check. If you succeed, you and the creature are both restrained until the grapple ends. Creatures that are one size larger than you don\'t automatically succeed on checks to escape your grapple.',
                'strength_requirement': 13,
                'dexterity_requirement': 0,
                'constitution_requirement': 0,
                'intelligence_requirement': 0,
                'wisdom_requirement': 0,
                'charisma_requirement': 0,
                'minimum_level': 4,
                'proficiency_requirements': '',
            },
            {
                'name': 'Heavy Armor Master',
                'description': 'You can use your armor to deflect strikes that would kill others. You gain the following benefits: Increase your Strength score by 1, to a maximum of 20. While you are wearing heavy armor, bludgeoning, piercing, and slashing damage that you take from nonmagical weapons is reduced by 3.',
                'strength_requirement': 0,
                'dexterity_requirement': 0,
                'constitution_requirement': 0,
                'intelligence_requirement': 0,
                'wisdom_requirement': 0,
                'charisma_requirement': 0,
                'minimum_level': 4,
                'proficiency_requirements': 'Heavy Armor',
                'ability_score_increase': 'STR',
            },
            {
                'name': 'Keen Mind',
                'description': 'You have a mind that can track time, direction, and detail with uncanny precision. You gain the following benefits: You always know which way is north. You always know the number of hours left before the next sunrise or sunset. You can accurately recall anything you have seen or heard within the past month.',
                'strength_requirement': 0,
                'dexterity_requirement': 0,
                'constitution_requirement': 0,
                'intelligence_requirement': 0,
                'wisdom_requirement': 0,
                'charisma_requirement': 0,
                'minimum_level': 4,
                'proficiency_requirements': '',
                'ability_score_increase': 'INT',
            },
            {
                'name': 'Linguist',
                'description': 'You have studied languages and codes, gaining the following benefits: Increase your Intelligence score by 1, to a maximum of 20. You learn three languages of your choice. You can ably create written ciphers. Others can\'t decipher a code you create unless you teach them, they succeed on an Intelligence check (DC equal to your Intelligence score + your proficiency bonus), or they use magic to decipher it.',
                'strength_requirement': 0,
                'dexterity_requirement': 0,
                'constitution_requirement': 0,
                'intelligence_requirement': 0,
                'wisdom_requirement': 0,
                'charisma_requirement': 0,
                'minimum_level': 4,
                'proficiency_requirements': '',
                'ability_score_increase': 'INT',
            },
            {
                'name': 'Savage Attacker',
                'description': 'Once per turn when you roll damage for a melee weapon attack, you can reroll the damage dice and use either total.',
                'strength_requirement': 0,
                'dexterity_requirement': 0,
                'constitution_requirement': 0,
                'intelligence_requirement': 0,
                'wisdom_requirement': 0,
                'charisma_requirement': 0,
                'minimum_level': 4,
                'proficiency_requirements': '',
            },
            {
                'name': 'Skilled',
                'description': 'You gain proficiency in any combination of three skills or tools of your choice.',
                'strength_requirement': 0,
                'dexterity_requirement': 0,
                'constitution_requirement': 0,
                'intelligence_requirement': 0,
                'wisdom_requirement': 0,
                'charisma_requirement': 0,
                'minimum_level': 4,
                'proficiency_requirements': '',
            },
            {
                'name': 'Skulker',
                'description': 'You are expert at slinking through shadows. You gain the following benefits: You can try to hide when you are lightly obscured from the creature from which you are hiding. When you are hidden from a creature and miss it with a ranged weapon attack, making the attack doesn\'t reveal your position. Dim light doesn\'t impose disadvantage on your Wisdom (Perception) checks relying on sight.',
                'strength_requirement': 0,
                'dexterity_requirement': 13,
                'constitution_requirement': 0,
                'intelligence_requirement': 0,
                'wisdom_requirement': 0,
                'charisma_requirement': 0,
                'minimum_level': 4,
                'proficiency_requirements': '',
            },
            {
                'name': 'Tavern Brawler',
                'description': 'Accustomed to rough-and-tumble fighting using whatever weapons happen to be at hand, you gain the following benefits: Increase your Strength or Constitution score by 1, to a maximum of 20. You are proficient with improvised weapons. Your unarmed strike uses a d4 for damage. When you hit a creature with an unarmed strike or an improvised weapon on your turn, you can use a bonus action to attempt to grapple the target.',
                'strength_requirement': 0,
                'dexterity_requirement': 0,
                'constitution_requirement': 0,
                'intelligence_requirement': 0,
                'wisdom_requirement': 0,
                'charisma_requirement': 0,
                'minimum_level': 4,
                'proficiency_requirements': '',
            },
            {
                'name': 'Weapon Master',
                'description': 'You have practiced extensively with a variety of weapons, gaining the following benefits: Increase your Strength or Dexterity score by 1, to a maximum of 20. You gain proficiency with four weapons of your choice.',
                'strength_requirement': 0,
                'dexterity_requirement': 0,
                'constitution_requirement': 0,
                'intelligence_requirement': 0,
                'wisdom_requirement': 0,
                'charisma_requirement': 0,
                'minimum_level': 4,
                'proficiency_requirements': '',
            },
        ]
        
        for feat_data in feats:
            feat, created = Feat.objects.get_or_create(
                name=feat_data['name'],
                defaults=feat_data
            )
            if created:
                self.stdout.write(self.style.SUCCESS(f'Created feat: {feat.name}'))
            else:
                self.stdout.write(f'Feat already exists: {feat.name}')
        
        self.stdout.write(
            self.style.SUCCESS(f'\nSuccessfully populated {len(feats)} feats!')
        )

