# Generated by Django 5.0.2 on 2025-10-30 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bestiary', '0004_condition_environment_enemy_alignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EncounterEnemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('initiative', models.IntegerField(default=0)),
                ('current_hp', models.IntegerField()),
                ('is_alive', models.BooleanField(default=True)),
                ('conditions', models.TextField(blank=True, help_text='Comma-separated list of conditions (e.g., stunned, poisoned)')),
                ('notes', models.TextField(blank=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemies', to='encounters.encounter')),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounter_instances', to='bestiary.enemy')),
            ],
        ),
    ]
