# Generated by Django 5.0.2 on 2026-01-15 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0006_enemy_enemy_cr_idx_enemy_enemy_type_idx_and_more'),
        ('encounters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncounterTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('humanoid', 'Humanoid Threats'), ('undead', 'Undead Hordes'), ('beast', 'Beast Packs'), ('aberration', 'Aberrations'), ('elemental', 'Elemental Forces'), ('fiend', 'Fiendish Incursions'), ('dragon', 'Draconic Encounters'), ('fey', 'Fey Tricksters'), ('giant', 'Giant Clans'), ('dungeon', 'Dungeon Denizens')], max_length=20)),
                ('description', models.TextField()),
                ('min_cr', models.IntegerField(default=0, help_text='Minimum challenge rating')),
                ('max_cr', models.IntegerField(default=30, help_text='Maximum challenge rating')),
                ('weight', models.IntegerField(default=100)),
                ('flavor_text', models.TextField(blank=True, help_text='Story description for DM')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='encounter',
            name='biome',
            field=models.CharField(blank=True, choices=[('forest', 'Forest'), ('desert', 'Desert'), ('mountain', 'Mountain'), ('swamp', 'Swamp'), ('plains', 'Plains'), ('coast', 'Coast'), ('arctic', 'Arctic'), ('underdark', 'Underdark'), ('urban', 'Urban'), ('dungeon', 'Dungeon')], help_text='Environment where encounter takes place', max_length=20),
        ),
        migrations.AddField(
            model_name='encounter',
            name='is_chaotic',
            field=models.BooleanField(default=False, help_text='True if this encounter mixes incompatible themes'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='narrative_justification',
            field=models.TextField(blank=True, help_text='Story reason for anomalies or chaotic encounters'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='theme',
            field=models.ForeignKey(blank=True, help_text='Thematic group this encounter belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters', to='encounters.encountertheme'),
        ),
        migrations.CreateModel(
            name='BiomeEncounterWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biome', models.CharField(choices=[('forest', 'Forest'), ('desert', 'Desert'), ('mountain', 'Mountain'), ('swamp', 'Swamp'), ('plains', 'Plains'), ('coast', 'Coast'), ('arctic', 'Arctic'), ('underdark', 'Underdark'), ('urban', 'Urban'), ('dungeon', 'Dungeon')], max_length=20)),
                ('category', models.CharField(choices=[('endemic', 'Endemic - 60%'), ('adapted', 'Adapted - 20%'), ('traveler', 'Traveler - 15%'), ('anomaly', 'Anomaly - 5%')], max_length=20)),
                ('weight', models.IntegerField(default=100, help_text='Relative likelihood')),
                ('narrative_reason', models.TextField(blank=True, help_text='Explanation for non-endemic encounters')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biome_weights', to='encounters.encountertheme')),
            ],
            options={
                'ordering': ['biome', 'category', 'theme'],
                'unique_together': {('biome', 'theme', 'category')},
            },
        ),
        migrations.CreateModel(
            name='EnemyThemeAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', 'Primary Threat'), ('elite', 'Elite Unit'), ('support', 'Support/Minion'), ('leader', 'Leader'), ('artillery', 'Ranged Attacker'), ('controller', 'Battlefield Control'), ('tank', 'Defensive Wall')], max_length=20)),
                ('weight', models.IntegerField(default=100, help_text='Likelihood of appearing in theme')),
                ('min_count', models.IntegerField(default=1, help_text='Minimum enemies of this type')),
                ('max_count', models.IntegerField(default=4, help_text='Maximum enemies of this type')),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_associations', to='bestiary.enemy')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemy_associations', to='encounters.encountertheme')),
            ],
            options={
                'ordering': ['theme', 'role', 'enemy'],
                'unique_together': {('theme', 'enemy', 'role')},
            },
        ),
        migrations.CreateModel(
            name='ThemeIncompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text="Why these themes don't mix")),
                ('allow_chaotic', models.BooleanField(default=True, help_text='Allow in chaotic encounters (5% chance)')),
                ('theme1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incompatible_with', to='encounters.encountertheme')),
                ('theme2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incompatible_as', to='encounters.encountertheme')),
            ],
            options={
                'unique_together': {('theme1', 'theme2')},
            },
        ),
    ]
