# Generated by Django 5.0.2 on 2026-01-12 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0007_campaigncharacter_gold'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encounter_number', models.IntegerField(help_text='Depth in the gauntlet when discovered')),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether merchant is still available for trading')),
                ('merchant_name', models.CharField(help_text='Randomly generated merchant name', max_length=100)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchants', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['encounter_number', '-discovered_at'],
                'unique_together': {('campaign', 'encounter_number')},
            },
        ),
        migrations.CreateModel(
            name='MerchantInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Number of this item available')),
                ('price', models.IntegerField(help_text='Price in gold pieces (GP)')),
                ('is_sold', models.BooleanField(default=False)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='merchants.merchantencounter')),
                ('purchased_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_items', to='campaigns.campaigncharacter')),
            ],
            options={
                'ordering': ['is_sold', '-price'],
            },
        ),
        migrations.CreateModel(
            name='MerchantTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='Item name at time of purchase', max_length=100)),
                ('price', models.IntegerField(help_text='Price paid in gold')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('campaign_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='campaigns.campaigncharacter')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.merchantinventoryitem')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='merchants.merchantencounter')),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
    ]
