# Generated by Django 6.0 on 2025-12-26 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bestiary', '0005_alter_enemy_ac_alter_enemy_hp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('acolyte', 'Acolyte'), ('criminal', 'Criminal'), ('folk-hero', 'Folk Hero'), ('noble', 'Noble'), ('sage', 'Sage'), ('soldier', 'Soldier'), ('hermit', 'Hermit'), ('outlander', 'Outlander'), ('entertainer', 'Entertainer'), ('guild-artisan', 'Guild Artisan'), ('charlatan', 'Charlatan'), ('sailor', 'Sailor')], max_length=20, unique=True)),
                ('skill_proficiencies', models.CharField(blank=True, max_length=100)),
                ('tool_proficiencies', models.CharField(blank=True, max_length=100)),
                ('languages', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('barbarian', 'Barbarian'), ('bard', 'Bard'), ('cleric', 'Cleric'), ('druid', 'Druid'), ('fighter', 'Fighter'), ('monk', 'Monk'), ('paladin', 'Paladin'), ('ranger', 'Ranger'), ('rogue', 'Rogue'), ('sorcerer', 'Sorcerer'), ('warlock', 'Warlock'), ('wizard', 'Wizard')], max_length=20, unique=True)),
                ('hit_dice', models.CharField(max_length=10)),
                ('primary_ability', models.CharField(max_length=3)),
                ('saving_throw_proficiencies', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('human', 'Human'), ('elf', 'Elf'), ('dwarf', 'Dwarf'), ('halfling', 'Halfling'), ('dragonborn', 'Dragonborn'), ('gnome', 'Gnome'), ('half-elf', 'Half-Elf'), ('half-orc', 'Half-Orc'), ('tiefling', 'Tiefling')], max_length=20, unique=True)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium')], default='M', max_length=1)),
                ('speed', models.IntegerField(default=30)),
                ('ability_score_increases', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium')], default='M', max_length=1)),
                ('alignment', models.CharField(choices=[('LG', 'Lawful Good'), ('NG', 'Neutral Good'), ('CG', 'Chaotic Good'), ('LN', 'Lawful Neutral'), ('N', 'Neutral'), ('CN', 'Chaotic Neutral'), ('LE', 'Lawful Evil'), ('NE', 'Neutral Evil'), ('CE', 'Chaotic Evil'), ('U', 'Unaligned')], default='N', max_length=2)),
                ('experience_points', models.IntegerField(default=0)),
                ('player_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('backstory', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='characters.characterbackground')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='characters.characterclass')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='characters.characterrace')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('feature_type', models.CharField(choices=[('class', 'Class Feature'), ('racial', 'Racial Feature'), ('background', 'Background Feature'), ('feat', 'Feat')], max_length=20)),
                ('description', models.TextField()),
                ('source', models.CharField(blank=True, max_length=100)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(default=10)),
                ('dexterity', models.IntegerField(default=10)),
                ('constitution', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('wisdom', models.IntegerField(default=10)),
                ('charisma', models.IntegerField(default=10)),
                ('hit_points', models.IntegerField()),
                ('max_hit_points', models.IntegerField()),
                ('armor_class', models.IntegerField()),
                ('speed', models.IntegerField(default=30)),
                ('initiative', models.IntegerField(default=0)),
                ('hit_dice_total', models.CharField(blank=True, max_length=20, null=True)),
                ('hit_dice_current', models.CharField(blank=True, max_length=20, null=True)),
                ('darkvision', models.IntegerField(default=0)),
                ('passive_perception', models.IntegerField(default=10)),
                ('passive_investigation', models.IntegerField(default=10)),
                ('passive_insight', models.IntegerField(default=10)),
                ('spell_save_dc', models.IntegerField(blank=True, null=True)),
                ('spell_attack_bonus', models.IntegerField(blank=True, null=True)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterProficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_type', models.CharField(choices=[('skill', 'Skill'), ('tool', 'Tool'), ('weapon', 'Weapon'), ('armor', 'Armor'), ('language', 'Language'), ('saving_throw', 'Saving Throw')], max_length=20)),
                ('proficiency_level', models.CharField(choices=[('proficient', 'Proficient'), ('expertise', 'Expertise')], default='proficient', max_length=20)),
                ('skill_name', models.CharField(blank=True, max_length=50, null=True)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ability_score', models.CharField(blank=True, max_length=3, null=True)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proficiencies', to='characters.character')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_proficiencies', to='bestiary.language')),
            ],
            options={
                'unique_together': {('character', 'proficiency_type', 'ability_score'), ('character', 'proficiency_type', 'item_name'), ('character', 'proficiency_type', 'language'), ('character', 'proficiency_type', 'skill_name')},
            },
        ),
        migrations.CreateModel(
            name='CharacterResistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resistance_type', models.CharField(choices=[('resistance', 'Resistance'), ('immunity', 'Immunity'), ('vulnerability', 'Vulnerability')], max_length=20)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resistances', to='characters.character')),
                ('damage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestiary.damagetype')),
            ],
            options={
                'unique_together': {('character', 'damage_type', 'resistance_type')},
            },
        ),
        migrations.CreateModel(
            name='CharacterSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(choices=[(0, 'Cantrip'), (1, '1st Level'), (2, '2nd Level'), (3, '3rd Level'), (4, '4th Level'), (5, '5th Level'), (6, '6th Level'), (7, '7th Level'), (8, '8th Level'), (9, '9th Level')])),
                ('school', models.CharField(blank=True, max_length=50)),
                ('is_prepared', models.BooleanField(default=False)),
                ('is_ritual', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spells', to='characters.character')),
            ],
            options={
                'unique_together': {('character', 'name')},
            },
        ),
    ]
