# Generated by Django 6.0 on 2025-12-26 20:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_equipped', models.BooleanField(default=False)),
                ('equipment_slot', models.CharField(choices=[('main_hand', 'Main Hand'), ('off_hand', 'Off Hand'), ('armor', 'Armor'), ('shield', 'Shield'), ('ring', 'Ring'), ('amulet', 'Amulet'), ('boots', 'Boots'), ('gloves', 'Gloves'), ('helmet', 'Helmet'), ('cloak', 'Cloak'), ('inventory', 'Inventory')], default='inventory', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_items', to='characters.character')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_items', to='items.item')),
            ],
            options={
                'ordering': ['equipment_slot', 'item__name'],
                'unique_together': {('character', 'item', 'equipment_slot')},
            },
        ),
    ]
