# Generated by Django 6.0 on 2025-12-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_character_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='subclass',
            field=models.CharField(blank=True, help_text="Character's subclass (e.g., 'Champion', 'Battle Master', 'College of Lore')", max_length=100, null=True),
        ),
    ]
