# Generated by Django 6.0 on 2025-12-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_feat_characterfeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterspell',
            name='in_spellbook',
            field=models.BooleanField(default=False),
        ),
    ]
