# Generated by Django 6.0 on 2025-12-28 12:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_add_spellbook_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('subclass', models.CharField(blank=True, help_text='Subclass for this class', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_levels', to='characters.character')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='character_levels', to='characters.characterclass')),
            ],
            options={
                'ordering': ['-level', 'character_class__name'],
                'unique_together': {('character', 'character_class')},
            },
        ),
    ]
