# Generated by Django 6.0 on 2025-12-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_add_multiclassing'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterstats',
            name='spell_slots',
            field=models.JSONField(blank=True, default=dict, help_text='Current spell slots remaining by level'),
        ),
    ]
