# Generated by Django 6.0 on 2025-12-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_add_spell_slots_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='pending_asi_levels',
            field=models.JSONField(blank=True, default=list, help_text='List of levels where ASI/Feat is pending player choice (e.g., [4, 8])'),
        ),
        migrations.AddField(
            model_name='character',
            name='pending_subclass_selection',
            field=models.BooleanField(default=False, help_text='True if character needs to select subclass'),
        ),
    ]
