# Generated by Django 5.0.2 on 2026-01-13 20:08

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_character_pending_asi_levels_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='experience_points',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddIndex(
            model_name='character',
            index=models.Index(fields=['user'], name='char_user_idx'),
        ),
        migrations.AddIndex(
            model_name='character',
            index=models.Index(fields=['level'], name='char_level_idx'),
        ),
        migrations.AddIndex(
            model_name='character',
            index=models.Index(fields=['character_class'], name='char_class_idx'),
        ),
        migrations.AddIndex(
            model_name='character',
            index=models.Index(fields=['race'], name='char_race_idx'),
        ),
        migrations.AddIndex(
            model_name='character',
            index=models.Index(fields=['-created_at'], name='char_created_idx'),
        ),
    ]
