# Generated by Django 5.0.2 on 2026-01-19 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_characterbuildersession'),
        ('spells', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterspell',
            name='spell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='known_by', to='spells.spell'),
        ),
    ]
