# Generated by Django 5.0.2 on 2026-01-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0012_characterspell_spell'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='hp_method',
            field=models.CharField(choices=[('fixed', 'Fixed (Max Roll)'), ('average', 'Average'), ('manual', 'Manual / Dice Roll')], default='fixed', help_text='Method used for HP calculation', max_length=10),
        ),
    ]
