# Generated by Django 5.0.2 on 2026-01-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0013_character_hp_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterrace',
            name='skill_proficiencies',
            field=models.CharField(blank=True, help_text="Comma-separated list of skills, e.g. 'Perception,Stealth'", max_length=100),
        ),
        migrations.AddField(
            model_name='characterrace',
            name='traits',
            field=models.JSONField(blank=True, default=list, help_text='List of racial traits'),
        ),
    ]
