# Generated by Django 5.0.2 on 2026-01-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0014_characterrace_skill_proficiencies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterbackground',
            name='feature_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='characterbackground',
            name='feature_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
