# Generated by Django 5.0.2 on 2026-01-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0015_characterbackground_feature_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='bonds',
            field=models.TextField(blank=True, help_text="Character's bonds (connections to people, places, or ideals)", null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='flaws',
            field=models.TextField(blank=True, help_text="Character's flaws or weaknesses", null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='ideals',
            field=models.TextField(blank=True, help_text="Character's ideals or beliefs", null=True),
        ),
    ]
