# Generated by Django 5.0.2 on 2026-01-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0016_character_bonds_character_flaws_character_ideals'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='pending_language_choices',
            field=models.IntegerField(default=0, help_text='Number of languages the character can select (e.g. from Linguist feat)'),
        ),
    ]
