# Generated by Django 5.0.2 on 2026-01-22 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0017_character_pending_language_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='copper_pieces',
            field=models.IntegerField(default=0, help_text='Copper pieces (cp)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='character',
            name='electrum_pieces',
            field=models.IntegerField(default=0, help_text='Electrum pieces (ep)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='character',
            name='gold_pieces',
            field=models.IntegerField(default=0, help_text='Gold pieces (gp)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='character',
            name='platinum_pieces',
            field=models.IntegerField(default=0, help_text='Platinum pieces (pp)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='character',
            name='silver_pieces',
            field=models.IntegerField(default=0, help_text='Silver pieces (sp)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
