# Generated by Django 5.0.2 on 2026-01-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0018_character_copper_pieces_character_electrum_pieces_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterstats',
            name='temporary_hit_points',
            field=models.IntegerField(default=0),
        ),
    ]
