# Generated by Django 5.0.2 on 2026-01-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0019_characterstats_temporary_hit_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='pending_spell_choices',
            field=models.JSONField(blank=True, default=dict, help_text="Config for pending spell selection e.g. {'count': 2, 'max_level': 2}"),
        ),
    ]
