# Generated by Django 5.0.2 on 2026-01-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0020_character_pending_spell_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterstats',
            name='expended_spell_slots',
            field=models.JSONField(blank=True, default=dict, help_text="Expended spell slots by level (e.g. {'1': 1})"),
        ),
        migrations.AddField(
            model_name='characterstats',
            name='hit_dice_used',
            field=models.IntegerField(default=0, help_text='Number of hit dice spent'),
        ),
        migrations.AlterField(
            model_name='characterstats',
            name='spell_slots',
            field=models.JSONField(blank=True, default=dict, help_text="Max spell slots available by level (e.g. {'1': 2})"),
        ),
    ]
