# Generated by Django 5.0.2 on 2026-01-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0021_characterstats_expended_spell_slots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterstats',
            name='ki_points_used',
            field=models.IntegerField(default=0, help_text='Number of Ki points spent'),
        ),
        migrations.AddField(
            model_name='characterstats',
            name='temp_hp',
            field=models.IntegerField(default=0, help_text='Temporary Hit Points'),
        ),
    ]
