# Generated by Django 5.0.2 on 2026-01-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0022_characterstats_ki_points_used_characterstats_temp_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='ruleset_version',
            field=models.CharField(choices=[('2014', '2014 Legacy'), ('2024', '2024 Standard')], default='2014', max_length=10),
        ),
        migrations.AddField(
            model_name='characterbackground',
            name='ability_score_options',
            field=models.JSONField(blank=True, default=dict, help_text="For 2024 rules: {'options': ['+2/+1', '+1/+1/+1'], 'stats': ['str', 'dex', ...]}"),
        ),
        migrations.AddField(
            model_name='characterbackground',
            name='source_ruleset',
            field=models.CharField(choices=[('2014', '2014'), ('2024', '2024'), ('all', 'All')], default='2014', max_length=10),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='source_ruleset',
            field=models.CharField(choices=[('2014', '2014'), ('2024', '2024'), ('all', 'All')], default='2014', max_length=10),
        ),
        migrations.AddField(
            model_name='characterrace',
            name='source_ruleset',
            field=models.CharField(choices=[('2014', '2014'), ('2024', '2024'), ('all', 'All')], default='2014', max_length=10),
        ),
    ]
