# Generated by Django 5.0.2 on 2026-01-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0023_character_ruleset_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterfeature',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text="List of available choices (e.g. ['Archery', 'Defense'])"),
        ),
        migrations.AddField(
            model_name='characterfeature',
            name='selection',
            field=models.CharField(blank=True, help_text="User's selection", max_length=100, null=True),
        ),
    ]
