# Generated by Django 5.0.2 on 2026-01-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0024_characterfeature_options_characterfeature_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterfeature',
            name='selection',
            field=models.JSONField(blank=True, default=list, help_text="User's selection (list of strings)", null=True),
        ),
    ]
