# Generated by Django 5.0.2 on 2026-01-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0025_alter_characterfeature_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterfeature',
            name='choice_limit',
            field=models.IntegerField(default=1, help_text='Number of choices allowed'),
        ),
    ]
