# Generated by Django 5.0.2 on 2026-01-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0026_characterfeature_choice_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='feat',
            name='category',
            field=models.CharField(choices=[('origin', 'Origin'), ('general', 'General'), ('fighting_style', 'Fighting Style'), ('epic_boon', 'Epic Boon'), ('other', 'Other')], default='other', help_text='Feat Category (2024 Rules)', max_length=20),
        ),
    ]
