# Generated by Django 5.0.2 on 2026-01-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0027_feat_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterfeat',
            name='choice_limit',
            field=models.IntegerField(default=1, help_text='Number of choices allowed'),
        ),
        migrations.AddField(
            model_name='characterfeat',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='List of available options for this feat'),
        ),
        migrations.AddField(
            model_name='characterfeat',
            name='selection',
            field=models.JSONField(blank=True, default=list, help_text="User's selected options"),
        ),
    ]
