# Generated by Django 5.0.2 on 2026-01-29 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0028_characterfeat_choice_limit_characterfeat_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='characterfeat',
            unique_together=set(),
        ),
    ]
