# Generated by Django 5.0.2 on 2026-01-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0029_alter_characterfeat_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterclass',
            name='num_skill_choices',
            field=models.IntegerField(default=2, help_text='Number of skills to choose'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='skill_proficiency_choices',
            field=models.TextField(blank=True, help_text='Comma-separated list of skills available to choose from'),
        ),
    ]
