# Generated by Django 5.0.2 on 2026-04-15 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0030_characterclass_num_skill_choices_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharacterBuilderSession',
        ),
    ]
