# Generated by Django 5.0.2 on 2026-01-12 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bestiary', '0005_alter_enemy_ac_alter_enemy_hp'),
        ('characters', '0009_character_pending_asi_levels_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly name for API reference', max_length=100, unique=True)),
                ('level', models.IntegerField(choices=[(0, 'Cantrip'), (1, '1st Level'), (2, '2nd Level'), (3, '3rd Level'), (4, '4th Level'), (5, '5th Level'), (6, '6th Level'), (7, '7th Level'), (8, '8th Level'), (9, '9th Level')], default=0)),
                ('school', models.CharField(choices=[('abjuration', 'Abjuration'), ('conjuration', 'Conjuration'), ('divination', 'Divination'), ('enchantment', 'Enchantment'), ('evocation', 'Evocation'), ('illusion', 'Illusion'), ('necromancy', 'Necromancy'), ('transmutation', 'Transmutation')], max_length=20)),
                ('casting_time', models.CharField(help_text="e.g., '1 action', '1 bonus action', '1 minute'", max_length=100)),
                ('range', models.CharField(help_text="e.g., 'Self', '60 feet', 'Touch'", max_length=100)),
                ('components', models.CharField(help_text='V, S, M components', max_length=100)),
                ('material', models.TextField(blank=True, help_text='Material component description if M is required')),
                ('duration', models.CharField(help_text="e.g., 'Instantaneous', '1 hour', 'Concentration, up to 1 minute'", max_length=100)),
                ('concentration', models.BooleanField(default=False)),
                ('ritual', models.BooleanField(default=False)),
                ('description', models.TextField(help_text='Full spell description')),
                ('higher_level', models.TextField(blank=True, help_text='Description of effects when cast at higher levels')),
                ('source', models.CharField(default='PHB', help_text='Source book (PHB, XGE, TCE, etc.)', max_length=50)),
                ('page', models.CharField(blank=True, help_text='Page number in source book', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classes', models.ManyToManyField(blank=True, help_text='Which classes can learn this spell', related_name='available_spells', to='characters.characterclass')),
            ],
            options={
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpellDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell_slot_level', models.IntegerField(help_text='Spell slot level used to cast')),
                ('damage_dice', models.CharField(help_text="e.g., '8d6', '3d8+3'", max_length=20)),
                ('damage_type', models.ForeignKey(blank=True, help_text='Type of damage dealt', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bestiary.damagetype')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_progression', to='spells.spell')),
            ],
            options={
                'ordering': ['spell', 'spell_slot_level'],
            },
        ),
        migrations.AddIndex(
            model_name='spell',
            index=models.Index(fields=['level', 'school'], name='spells_spel_level_9b5733_idx'),
        ),
        migrations.AddIndex(
            model_name='spell',
            index=models.Index(fields=['name'], name='spells_spel_name_eef903_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='spelldamage',
            unique_together={('spell', 'spell_slot_level')},
        ),
    ]
