# Generated by Django 5.0.2 on 2026-01-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='source_ruleset',
            field=models.CharField(choices=[('2014', '2014 Rules'), ('2024', '2024 Rules')], default='2014', help_text='The ruleset version this spell belongs to.', max_length=10),
        ),
    ]
