# Generated by Django 5.0.2 on 2026-09-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0002_spell_source_ruleset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='casting_time',
            field=models.CharField(help_text="e.g., '1 action', '1 bonus action', '1 minute'", max_length=200),
        ),
    ]
