# Generated by Django 5.0.2 on 2025-10-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hp', models.IntegerField()),
                ('ac', models.IntegerField()),
                ('attack_bonus', models.IntegerField()),
                ('damage', models.CharField(max_length=50)),
            ],
        ),
    ]
