# Generated by Django 5.0.2 on 2025-10-27 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemy',
            name='attack_bonus',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='damage',
        ),
        migrations.AddField(
            model_name='enemy',
            name='challenge_rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='EnemyAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='bestiary.enemy')),
            ],
        ),
        migrations.CreateModel(
            name='EnemyAttack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bonus', models.IntegerField()),
                ('damage', models.CharField(max_length=50)),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacks', to='bestiary.enemy')),
            ],
        ),
        migrations.CreateModel(
            name='EnemySpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('save_dc', models.IntegerField(blank=True, null=True)),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spells', to='bestiary.enemy')),
            ],
        ),
        migrations.CreateModel(
            name='EnemySpellSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('uses', models.IntegerField()),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='bestiary.enemyspell')),
            ],
        ),
    ]
