# Generated by Django 5.0.2 on 2025-10-27 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0002_remove_enemy_attack_bonus_remove_enemy_damage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnemyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(default=10)),
                ('dexterity', models.IntegerField(default=10)),
                ('constitution', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('wisdom', models.IntegerField(default=10)),
                ('charisma', models.IntegerField(default=10)),
                ('hit_points', models.IntegerField()),
                ('armor_class', models.IntegerField()),
                ('speed', models.CharField(blank=True, max_length=100, null=True)),
                ('str_save', models.IntegerField(blank=True, null=True)),
                ('dex_save', models.IntegerField(blank=True, null=True)),
                ('con_save', models.IntegerField(blank=True, null=True)),
                ('int_save', models.IntegerField(blank=True, null=True)),
                ('wis_save', models.IntegerField(blank=True, null=True)),
                ('cha_save', models.IntegerField(blank=True, null=True)),
                ('athletics', models.IntegerField(blank=True, null=True)),
                ('acrobatics', models.IntegerField(blank=True, null=True)),
                ('sleight_of_hand', models.IntegerField(blank=True, null=True)),
                ('stealth', models.IntegerField(blank=True, null=True)),
                ('arcana', models.IntegerField(blank=True, null=True)),
                ('history', models.IntegerField(blank=True, null=True)),
                ('investigation', models.IntegerField(blank=True, null=True)),
                ('nature', models.IntegerField(blank=True, null=True)),
                ('religion', models.IntegerField(blank=True, null=True)),
                ('animal_handling', models.IntegerField(blank=True, null=True)),
                ('insight', models.IntegerField(blank=True, null=True)),
                ('medicine', models.IntegerField(blank=True, null=True)),
                ('perception', models.IntegerField(blank=True, null=True)),
                ('survival', models.IntegerField(blank=True, null=True)),
                ('deception', models.IntegerField(blank=True, null=True)),
                ('intimidation', models.IntegerField(blank=True, null=True)),
                ('performance', models.IntegerField(blank=True, null=True)),
                ('persuasion', models.IntegerField(blank=True, null=True)),
                ('darkvision', models.CharField(blank=True, max_length=50, null=True)),
                ('blindsight', models.CharField(blank=True, max_length=50, null=True)),
                ('tremorsense', models.CharField(blank=True, max_length=50, null=True)),
                ('truesight', models.CharField(blank=True, max_length=50, null=True)),
                ('passive_perception', models.IntegerField(blank=True, null=True)),
                ('spell_save_dc', models.IntegerField(blank=True, null=True)),
                ('spell_attack_bonus', models.IntegerField(blank=True, null=True)),
                ('enemy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='bestiary.enemy')),
            ],
        ),
        migrations.CreateModel(
            name='EnemyResistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resistance_type', models.CharField(choices=[('resistance', 'Resistance'), ('immunity', 'Immunity'), ('vulnerability', 'Vulnerability')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('damage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestiary.damagetype')),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resistances', to='bestiary.enemy')),
            ],
            options={
                'unique_together': {('enemy', 'damage_type', 'resistance_type')},
            },
        ),
        migrations.CreateModel(
            name='EnemyLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='bestiary.enemy')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestiary.language')),
            ],
            options={
                'unique_together': {('enemy', 'language')},
            },
        ),
    ]
