# Generated by Django 5.0.2 on 2025-10-27 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0003_damagetype_language_enemystats_enemyresistance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('blinded', 'Blinded'), ('charmed', 'Charmed'), ('deafened', 'Deafened'), ('frightened', 'Frightened'), ('grappled', 'Grappled'), ('incapacitated', 'Incapacitated'), ('invisible', 'Invisible'), ('paralyzed', 'Paralyzed'), ('petrified', 'Petrified'), ('poisoned', 'Poisoned'), ('prone', 'Prone'), ('restrained', 'Restrained'), ('stunned', 'Stunned'), ('unconscious', 'Unconscious'), ('exhaustion', 'Exhaustion')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('arctic', 'Arctic'), ('coastal', 'Coastal'), ('desert', 'Desert'), ('forest', 'Forest'), ('grassland', 'Grassland'), ('hill', 'Hill'), ('mountain', 'Mountain'), ('swamp', 'Swamp'), ('underdark', 'Underdark'), ('underwater', 'Underwater'), ('urban', 'Urban'), ('any', 'Any')], max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='enemy',
            name='alignment',
            field=models.CharField(choices=[('LG', 'Lawful Good'), ('NG', 'Neutral Good'), ('CG', 'Chaotic Good'), ('LN', 'Lawful Neutral'), ('N', 'Neutral'), ('CN', 'Chaotic Neutral'), ('LE', 'Lawful Evil'), ('NE', 'Neutral Evil'), ('CE', 'Chaotic Evil'), ('U', 'Unaligned')], default='N', max_length=2),
        ),
        migrations.AddField(
            model_name='enemy',
            name='creature_type',
            field=models.CharField(choices=[('aberration', 'Aberration'), ('beast', 'Beast'), ('celestial', 'Celestial'), ('construct', 'Construct'), ('dragon', 'Dragon'), ('elemental', 'Elemental'), ('fey', 'Fey'), ('fiend', 'Fiend'), ('giant', 'Giant'), ('humanoid', 'Humanoid'), ('monstrosity', 'Monstrosity'), ('ooze', 'Ooze'), ('plant', 'Plant'), ('undead', 'Undead')], default='humanoid', max_length=20),
        ),
        migrations.AddField(
            model_name='enemy',
            name='size',
            field=models.CharField(choices=[('T', 'Tiny'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('H', 'Huge'), ('G', 'Gargantuan')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='enemystats',
            name='hit_dice',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='enemystats',
            name='hit_dice_average',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enemystats',
            name='proficiency_bonus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EnemyLegendaryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cost', models.IntegerField(default=1)),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legendary_actions', to='bestiary.enemy')),
            ],
        ),
        migrations.CreateModel(
            name='EnemyTreasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treasure_type', models.CharField(choices=[('individual', 'Individual'), ('hoard', 'Hoard'), ('both', 'Both')], max_length=10)),
                ('description', models.TextField()),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasure', to='bestiary.enemy')),
            ],
        ),
        migrations.CreateModel(
            name='EnemyConditionImmunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestiary.condition')),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_immunities', to='bestiary.enemy')),
            ],
            options={
                'unique_together': {('enemy', 'condition')},
            },
        ),
        migrations.CreateModel(
            name='EnemyEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='bestiary.enemy')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestiary.environment')),
            ],
            options={
                'unique_together': {('enemy', 'environment')},
            },
        ),
    ]
