# Generated by Django 6.0 on 2025-12-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0004_condition_environment_enemy_alignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemy',
            name='ac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='hp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
