# Generated by Django 5.0.2 on 2026-01-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0005_alter_enemy_ac_alter_enemy_hp'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='enemy',
            index=models.Index(fields=['challenge_rating'], name='enemy_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='enemy',
            index=models.Index(fields=['creature_type'], name='enemy_type_idx'),
        ),
        migrations.AddIndex(
            model_name='enemy',
            index=models.Index(fields=['name'], name='enemy_name_idx'),
        ),
    ]
