# Generated by Django 5.0.2 on 2026-09-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0006_enemy_enemy_cr_idx_enemy_enemy_type_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagetype',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='enemyability',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='enemyattack',
            name='damage',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enemyattack',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='enemylegendaryaction',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
