# Generated by Django 5.0.2 on 2026-09-18 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0007_alter_damagetype_name_alter_enemyability_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnemyAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('action_type', models.CharField(choices=[('action', 'Action'), ('bonus_action', 'Bonus Action'), ('reaction', 'Reaction'), ('legendary_action', 'Legendary Action'), ('special', 'Special')], default='action', max_length=20)),
                ('attack_type', models.CharField(choices=[('melee_weapon', 'Melee Weapon Attack'), ('ranged_weapon', 'Ranged Weapon Attack'), ('melee_spell', 'Melee Spell Attack'), ('ranged_spell', 'Ranged Spell Attack'), ('saving_throw', 'Saving Throw'), ('utility', 'Utility')], default='melee_weapon', max_length=20)),
                ('attack_bonus', models.IntegerField(blank=True, null=True)),
                ('reach_or_range', models.CharField(blank=True, default='', max_length=100)),
                ('saving_throw_dc', models.IntegerField(blank=True, null=True)),
                ('saving_throw_ability', models.CharField(blank=True, choices=[('STR', 'Strength'), ('DEX', 'Dexterity'), ('CON', 'Constitution'), ('INT', 'Intelligence'), ('WIS', 'Wisdom'), ('CHA', 'Charisma')], max_length=3, null=True)),
                ('half_damage_on_save', models.BooleanField(default=False)),
                ('condition_save_end', models.BooleanField(default=False)),
                ('has_recharge', models.BooleanField(default=False)),
                ('recharge_min_roll', models.IntegerField(blank=True, null=True)),
                ('target_count_or_area', models.CharField(blank=True, default='', max_length=100)),
                ('legendary_cost', models.IntegerField(default=1)),
                ('conditions_inflicted', models.ManyToManyField(blank=True, related_name='inflicted_by_actions', to='bestiary.condition')),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='bestiary.enemy')),
            ],
        ),
        migrations.CreateModel(
            name='EnemyActionDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dice_count', models.IntegerField(default=1)),
                ('dice_sides', models.IntegerField(default=6)),
                ('damage_bonus', models.IntegerField(default=0)),
                ('is_secondary', models.BooleanField(default=False)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_rolls', to='bestiary.enemyaction')),
                ('damage_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bestiary.damagetype')),
            ],
        ),
        migrations.CreateModel(
            name='EnemyMultiattack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='')),
                ('action_count', models.IntegerField(default=2)),
                ('sequence', models.JSONField(blank=True, default=list)),
                ('enemy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multiattack', to='bestiary.enemy')),
            ],
        ),
        migrations.CreateModel(
            name='EnemyTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('trait_type', models.CharField(blank=True, default='', max_length=50)),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='bestiary.enemy')),
            ],
        ),
        migrations.AddIndex(
            model_name='enemyaction',
            index=models.Index(fields=['enemy', 'action_type'], name='enemy_action_type_idx'),
        ),
        migrations.AddIndex(
            model_name='enemyaction',
            index=models.Index(fields=['name'], name='enemy_action_name_idx'),
        ),
        migrations.AddIndex(
            model_name='enemytrait',
            index=models.Index(fields=['enemy', 'trait_type'], name='enemy_trait_type_idx'),
        ),
    ]
