# Generated by Django 6.0 on 2025-12-26 20:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bestiary', '0005_alter_enemy_ac_alter_enemy_hp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=2, default=0, help_text='Weight in pounds', max_digits=6)),
                ('value', models.IntegerField(default=0, help_text='Value in gold pieces')),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('very_rare', 'Very Rare'), ('legendary', 'Legendary'), ('artifact', 'Artifact')], default='common', max_length=20)),
                ('is_magical', models.BooleanField(default=False)),
                ('requires_attunement', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Item Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Item Properties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.item')),
                ('armor_type', models.CharField(choices=[('light', 'Light Armor'), ('medium', 'Medium Armor'), ('heavy', 'Heavy Armor'), ('shield', 'Shield')], max_length=20)),
                ('base_ac', models.IntegerField(help_text='Base AC', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('max_dex_bonus', models.IntegerField(blank=True, help_text='Maximum DEX bonus (null = unlimited)', null=True)),
                ('min_strength', models.IntegerField(default=0, help_text='Minimum STR requirement')),
                ('stealth_disadvantage', models.BooleanField(default=False, help_text='Disadvantage on stealth checks')),
            ],
            options={
                'ordering': ['armor_type', 'name'],
            },
            bases=('items.item',),
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.item')),
                ('consumable_type', models.CharField(choices=[('potion', 'Potion'), ('scroll', 'Scroll'), ('food', 'Food'), ('other', 'Other')], default='other', max_length=20)),
                ('effect', models.TextField(help_text="Description of the item's effect")),
                ('duration', models.CharField(blank=True, help_text="Duration of effect, e.g., '1 hour'", max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=('items.item',),
        ),
        migrations.CreateModel(
            name='MagicItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.item')),
                ('attunement_required', models.BooleanField(default=False)),
                ('charges', models.IntegerField(blank=True, help_text='Number of charges (null = unlimited)', null=True)),
                ('charges_per_day', models.IntegerField(default=0, help_text='Charges regained per day')),
                ('spell_effect', models.TextField(blank=True, help_text='Spell effect description')),
                ('bonus_to_hit', models.IntegerField(default=0, help_text='Bonus to attack rolls')),
                ('bonus_to_damage', models.IntegerField(default=0, help_text='Bonus to damage rolls')),
                ('bonus_to_ac', models.IntegerField(default=0, help_text='Bonus to AC')),
                ('bonus_to_saves', models.IntegerField(default=0, help_text='Bonus to saving throws')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=('items.item',),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.itemcategory'),
        ),
        migrations.AddField(
            model_name='item',
            name='properties',
            field=models.ManyToManyField(blank=True, related_name='items', to='items.itemproperty'),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.item')),
                ('weapon_type', models.CharField(choices=[('simple_melee', 'Simple Melee'), ('simple_ranged', 'Simple Ranged'), ('martial_melee', 'Martial Melee'), ('martial_ranged', 'Martial Ranged')], max_length=20)),
                ('damage_dice', models.CharField(help_text="e.g., '1d6', '2d4'", max_length=20)),
                ('versatile_damage', models.CharField(blank=True, help_text="Damage when used two-handed, e.g., '1d10'", max_length=20)),
                ('range_normal', models.IntegerField(default=0, help_text='Normal range in feet (0 for melee)')),
                ('range_long', models.IntegerField(default=0, help_text='Long range in feet (0 for melee)')),
                ('finesse', models.BooleanField(default=False, help_text='Can use DEX instead of STR')),
                ('thrown', models.BooleanField(default=False, help_text='Can be thrown')),
                ('ammunition', models.BooleanField(default=False, help_text='Requires ammunition')),
                ('loading', models.BooleanField(default=False, help_text='Requires loading')),
                ('two_handed', models.BooleanField(default=False, help_text='Requires two hands')),
                ('heavy', models.BooleanField(default=False, help_text='Heavy weapon')),
                ('light', models.BooleanField(default=False, help_text='Light weapon')),
                ('reach', models.BooleanField(default=False, help_text='Has reach')),
                ('damage_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bestiary.damagetype')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=('items.item',),
        ),
    ]
