# Generated by Django 5.0.2 on 2026-01-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='mastery_property',
            field=models.CharField(blank=True, help_text='Weapon Mastery Property (2024 Rules): Cleave, Graze, Nick, Push, Sap, Slow, Topple, Vex', max_length=20, null=True),
        ),
    ]
