# Generated by Django 5.0.2 on 2026-09-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_populate_standard_armors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='weapon_type',
            field=models.CharField(choices=[('simple_melee', 'Simple Melee'), ('simple_ranged', 'Simple Ranged'), ('martial_melee', 'Martial Melee'), ('martial_ranged', 'Martial Ranged')], max_length=50),
        ),
    ]
