# Generated by Django 6.0 on 2025-12-26 11:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bestiary', '0005_alter_enemy_ac_alter_enemy_hp'),
        ('characters', '0001_initial'),
        ('encounters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('active', 'Active'), ('ended', 'Ended')], default='preparing', max_length=20)),
                ('current_round', models.IntegerField(default=0)),
                ('current_turn_index', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combat_sessions', to='encounters.encounter')),
            ],
        ),
        migrations.CreateModel(
            name='CombatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_type', models.CharField(choices=[('character', 'Character'), ('enemy', 'Enemy')], max_length=20)),
                ('initiative', models.IntegerField(default=0)),
                ('current_hp', models.IntegerField()),
                ('max_hp', models.IntegerField()),
                ('armor_class', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('action_used', models.BooleanField(default=False)),
                ('bonus_action_used', models.BooleanField(default=False)),
                ('reaction_used', models.BooleanField(default=False)),
                ('movement_used', models.IntegerField(default=0)),
                ('death_save_successes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('death_save_failures', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('notes', models.TextField(blank=True)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combat_participations', to='characters.character')),
                ('conditions', models.ManyToManyField(blank=True, related_name='combat_participants', to='bestiary.condition')),
                ('encounter_enemy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combat_participations', to='encounters.encounterenemy')),
                ('combat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='combat.combatsession')),
            ],
            options={
                'ordering': ['-initiative', 'id'],
                'unique_together': {('combat_session', 'character', 'encounter_enemy')},
            },
        ),
        migrations.CreateModel(
            name='CombatAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('attack', 'Attack'), ('spell', 'Spell'), ('move', 'Move'), ('dash', 'Dash'), ('dodge', 'Dodge'), ('disengage', 'Disengage'), ('help', 'Help'), ('hide', 'Hide'), ('ready', 'Ready'), ('search', 'Search'), ('use_object', 'Use Object'), ('other', 'Other')], max_length=20)),
                ('attack_name', models.CharField(blank=True, max_length=100)),
                ('attack_roll', models.IntegerField(blank=True, null=True)),
                ('attack_modifier', models.IntegerField(blank=True, null=True)),
                ('attack_total', models.IntegerField(blank=True, null=True)),
                ('hit', models.BooleanField(blank=True, null=True)),
                ('damage_roll', models.CharField(blank=True, max_length=100)),
                ('damage_amount', models.IntegerField(blank=True, null=True)),
                ('critical', models.BooleanField(default=False)),
                ('save_type', models.CharField(blank=True, max_length=3)),
                ('save_dc', models.IntegerField(blank=True, null=True)),
                ('save_roll', models.IntegerField(blank=True, null=True)),
                ('save_success', models.BooleanField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('round_number', models.IntegerField()),
                ('turn_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('damage_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bestiary.damagetype')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_taken', to='combat.combatparticipant')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_received', to='combat.combatparticipant')),
                ('combat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='combat.combatsession')),
            ],
            options={
                'ordering': ['-round_number', '-turn_number', '-created_at'],
            },
        ),
    ]
