# Generated by Django 6.0 on 2025-12-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combataction',
            name='is_legendary_action',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='combataction',
            name='is_opportunity_attack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='combataction',
            name='is_reaction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='combataction',
            name='legendary_action_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='concentration_spell',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='is_concentrating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='legendary_actions_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='legendary_actions_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='combataction',
            name='action_type',
            field=models.CharField(choices=[('attack', 'Attack'), ('spell', 'Spell'), ('move', 'Move'), ('dash', 'Dash'), ('dodge', 'Dodge'), ('disengage', 'Disengage'), ('help', 'Help'), ('hide', 'Hide'), ('ready', 'Ready'), ('search', 'Search'), ('use_object', 'Use Object'), ('opportunity_attack', 'Opportunity Attack'), ('reaction', 'Reaction'), ('legendary_action', 'Legendary Action'), ('death_save', 'Death Saving Throw'), ('concentration_check', 'Concentration Check'), ('other', 'Other')], max_length=20),
        ),
    ]
