# Generated by Django 6.0 on 2025-12-26 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0002_combataction_is_legendary_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rounds', models.IntegerField(default=0)),
                ('total_turns', models.IntegerField(default=0)),
                ('duration_seconds', models.IntegerField(default=0, help_text='Real-time duration in seconds')),
                ('total_damage_dealt', models.IntegerField(default=0)),
                ('total_damage_received', models.IntegerField(default=0)),
                ('total_healing', models.IntegerField(default=0)),
                ('actions_by_type', models.JSONField(default=dict, help_text='Count of actions by type')),
                ('damage_by_type', models.JSONField(default=dict, help_text='Damage totals by damage type')),
                ('spells_cast', models.JSONField(default=dict, help_text='Spells cast with counts')),
                ('participant_stats', models.JSONField(default=dict, help_text='Statistics per participant')),
                ('victors', models.JSONField(default=list, help_text='List of participant IDs who survived')),
                ('casualties', models.JSONField(default=list, help_text='List of participant IDs who died/unconscious')),
                ('share_token', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('combat_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='combat.combatsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
