# Generated by Django 6.0 on 2025-12-28 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0005_alter_enemy_ac_alter_enemy_hp'),
        ('combat', '0003_combatlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applied_round', models.IntegerField(default=1)),
                ('applied_turn', models.IntegerField(default=1)),
                ('duration_type', models.CharField(choices=[('instant', 'Instant'), ('turn', 'Turn'), ('round', 'Round'), ('spell', 'Spell'), ('saving_throw', 'Saving Throw'), ('concentration', 'Concentration')], default='instant', max_length=20)),
                ('duration_rounds', models.IntegerField(default=0, help_text='Number of rounds (0 = until removed manually)')),
                ('expires_at_round', models.IntegerField(blank=True, help_text='Round when condition expires', null=True)),
                ('source_type', models.CharField(blank=True, help_text="e.g., 'spell', 'ability', 'attack'", max_length=50)),
                ('source_name', models.CharField(blank=True, help_text="e.g., 'Hold Person', 'Stunning Strike'", max_length=100)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('removal_reason', models.CharField(blank=True, help_text="e.g., 'end_of_turn', 'saving_throw_success'", max_length=50)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestiary.condition')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_applications', to='combat.combatparticipant')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('participant', 'condition', 'applied_at')},
            },
        ),
    ]
