# Generated by Django 6.0 on 2025-12-28 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0004_add_condition_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_type', models.CharField(choices=[('terrain', 'Terrain'), ('cover', 'Cover'), ('lighting', 'Lighting'), ('weather', 'Weather'), ('hazard', 'Hazard')], max_length=20)),
                ('terrain_type', models.CharField(blank=True, choices=[('rubble', 'Rubble'), ('mud', 'Mud'), ('snow', 'Snow'), ('thick_vegetation', 'Thick Vegetation'), ('ice', 'Ice'), ('swamp', 'Swamp'), ('quicksand', 'Quicksand')], max_length=20, null=True)),
                ('cover_type', models.CharField(blank=True, choices=[('half', 'Half Cover'), ('three_quarters', 'Three-Quarters Cover'), ('full', 'Full Cover')], max_length=20, null=True)),
                ('cover_area_x', models.IntegerField(blank=True, help_text='X coordinate of cover area', null=True)),
                ('cover_area_y', models.IntegerField(blank=True, help_text='Y coordinate of cover area', null=True)),
                ('cover_area_radius', models.IntegerField(blank=True, help_text='Radius of cover area in feet', null=True)),
                ('lighting_type', models.CharField(blank=True, choices=[('bright_light', 'Bright Light'), ('dim_light', 'Dim Light'), ('darkness', 'Darkness'), ('magical_darkness', 'Magical Darkness')], max_length=20, null=True)),
                ('lighting_area_x', models.IntegerField(blank=True, null=True)),
                ('lighting_area_y', models.IntegerField(blank=True, null=True)),
                ('lighting_area_radius', models.IntegerField(blank=True, null=True)),
                ('weather_type', models.CharField(blank=True, choices=[('clear', 'Clear'), ('light_rain', 'Light Rain'), ('heavy_rain', 'Heavy Rain'), ('fog', 'Fog'), ('heavy_fog', 'Heavy Fog'), ('snow', 'Snow'), ('strong_wind', 'Strong Wind')], max_length=20, null=True)),
                ('hazard_type', models.CharField(blank=True, choices=[('lava', 'Lava'), ('acid', 'Acid'), ('poison_gas', 'Poison Gas'), ('spike_pit', 'Spike Pit'), ('electrified_water', 'Electrified Water')], max_length=20, null=True)),
                ('hazard_area_x', models.IntegerField(blank=True, null=True)),
                ('hazard_area_y', models.IntegerField(blank=True, null=True)),
                ('hazard_area_radius', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('combat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environmental_effects', to='combat.combatsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0, help_text='X coordinate in feet')),
                ('y', models.IntegerField(default=0, help_text='Y coordinate in feet')),
                ('z', models.IntegerField(default=0, help_text='Z coordinate (height) in feet')),
                ('current_terrain', models.CharField(blank=True, max_length=20, null=True)),
                ('current_cover', models.CharField(blank=True, max_length=20, null=True)),
                ('current_lighting', models.CharField(blank=True, max_length=20, null=True)),
                ('current_hazards', models.JSONField(blank=True, default=list, help_text='List of hazard types at this position')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='combat.combatparticipant')),
            ],
        ),
    ]
