# Generated by Django 6.0 on 2025-12-28 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0005_add_environmental_effects'),
        ('encounters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatsession',
            name='is_practice',
            field=models.BooleanField(default=False, help_text='True if this is a practice/simulation session'),
        ),
        migrations.AlterField(
            model_name='combatsession',
            name='encounter',
            field=models.ForeignKey(blank=True, help_text='Optional encounter. If null, this is a practice/simulation session.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combat_sessions', to='encounters.encounter'),
        ),
    ]
