# Generated by Django 5.0.2 on 2026-01-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0006_add_practice_mode'),
        ('encounters', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='combatsession',
            index=models.Index(fields=['encounter', 'status'], name='combat_enc_status_idx'),
        ),
        migrations.AddIndex(
            model_name='combatsession',
            index=models.Index(fields=['status'], name='combat_status_idx'),
        ),
        migrations.AddIndex(
            model_name='combatsession',
            index=models.Index(fields=['-started_at'], name='combat_started_idx'),
        ),
    ]
