# Generated by Django 5.0.2 on 2026-01-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0007_combatsession_combat_enc_status_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatparticipant',
            name='spell_uses_remaining',
            field=models.JSONField(blank=True, default=dict, help_text="Tracks spell uses for enemy spellcasters. Format: {'Fireball': 3, 'Power Word Kill': 1}"),
        ),
    ]
