# Generated by Django 5.0.2 on 2026-01-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0008_combatparticipant_spell_uses_remaining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combataction',
            name='save_type',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
