# Generated by Django 5.0.2 on 2026-01-15 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0009_alter_combataction_save_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatparticipant',
            name='cover_type',
            field=models.CharField(choices=[('none', 'No Cover'), ('half', 'Half Cover'), ('three_quarters', 'Three-Quarters Cover'), ('full', 'Full Cover')], default='none', help_text='Type of cover this participant has', max_length=20),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='grappled_by',
            field=models.ForeignKey(blank=True, help_text='Participant who has grappled this one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grappling_targets', to='combat.combatparticipant'),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='is_grappling',
            field=models.BooleanField(default=False, help_text='True if this participant is grappling someone'),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='position_x',
            field=models.IntegerField(default=0, help_text='X coordinate on battlefield grid (in feet)'),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='position_y',
            field=models.IntegerField(default=0, help_text='Y coordinate on battlefield grid (in feet)'),
        ),
    ]
