# Generated by Django 5.0.2 on 2026-01-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0010_combatparticipant_cover_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatparticipant',
            name='name',
            field=models.CharField(blank=True, help_text='Optional name override for practice mode', max_length=100),
        ),
    ]
