# Generated by Django 5.0.2 on 2026-01-19 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0011_combatparticipant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combataction',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_taken', to='combat.combatparticipant'),
        ),
    ]
