# Generated by Django 5.0.2 on 2026-02-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0012_alter_combataction_actor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combataction',
            options={'ordering': ['round_number', 'turn_number', 'created_at']},
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='attacks_remaining',
            field=models.IntegerField(default=1),
        ),
    ]
