# Generated by Django 5.0.2 on 2026-09-17 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0013_add_attacks_remaining'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='combatsession',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this combat session', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combat_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
