# Generated by Django 5.0.2 on 2026-09-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0014_combatsession_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatparticipant',
            name='recharge_state',
            field=models.JSONField(blank=True, default=dict, help_text='Tracks recharge ability states for monsters.'),
        ),
    ]
