# Generated by Django 5.0.2 on 2026-09-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0015_combatparticipant_recharge_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatparticipant',
            name='feature_uses',
            field=models.JSONField(blank=True, default=dict, help_text='Tracks active combat feature uses, e.g. lay_on_hands_pool, second_wind, rage_uses'),
        ),
    ]
