# Generated by Django 5.0.2 on 2026-09-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0016_combatparticipant_feature_uses'),
    ]

    operations = [
        migrations.AddField(
            model_name='combataction',
            name='is_advantage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='combataction',
            name='is_disadvantage',
            field=models.BooleanField(default=False),
        ),
    ]
