# Generated by Django 5.2.17 on 2026-10-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0017_combataction_is_advantage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatparticipant',
            name='altitude',
            field=models.IntegerField(default=0, help_text='Current altitude above ground in feet (Z-axis)'),
        ),
        migrations.AddField(
            model_name='combatparticipant',
            name='is_flying',
            field=models.BooleanField(default=False, help_text='True if participant is currently airborne'),
        ),
    ]
