# Generated by Django 5.0.2 on 2026-09-18 19:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0033_characteritem_is_attuned'),
        ('combat', '0015_combatparticipant_recharge_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GauntletRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='The Gauntlet', max_length=200)),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('active', 'Active'), ('respite', 'Respite'), ('completed', 'Completed'), ('failed', 'Failed')], default='preparing', max_length=20)),
                ('theme', models.CharField(choices=[('colosseum', 'Colosseum of Blades'), ('crypt', 'Crypt of the Undead'), ('inferno', 'Infernal Pit'), ('wilds', 'Savage Wilds'), ('dungeon', 'Sunken Dungeon')], default='colosseum', max_length=50)),
                ('party_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('party_size', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('current_wave', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_waves', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_endless', models.BooleanField(default=False, help_text='True if continuing past Wave 10 into endless overtime')),
                ('score', models.IntegerField(default=0)),
                ('enemies_killed', models.IntegerField(default=0)),
                ('damage_dealt', models.IntegerField(default=0)),
                ('turns_elapsed', models.IntegerField(default=0)),
                ('active_boons', models.JSONField(blank=True, default=list, help_text='Active tactical buffs for the next wave')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_combat_session', models.ForeignKey(blank=True, help_text='Combat session representing the active wave', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gauntlet_runs', to='combat.combatsession')),
                ('user', models.ForeignKey(blank=True, help_text='User who owns this Gauntlet run', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gauntlet_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GauntletSnapshotHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('character_class', models.CharField(blank=True, max_length=50)),
                ('level', models.IntegerField(default=1)),
                ('current_hp', models.IntegerField(default=10)),
                ('max_hp', models.IntegerField(default=10)),
                ('temp_hp', models.IntegerField(default=0)),
                ('hit_dice_remaining', models.IntegerField(default=1)),
                ('hit_dice_total', models.IntegerField(default=1)),
                ('hit_die_type', models.CharField(default='d8', max_length=10)),
                ('spell_slots', models.JSONField(blank=True, default=dict)),
                ('is_alive', models.BooleanField(default=True)),
                ('death_saves', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gauntlet_snapshots', to='characters.character')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_heroes', to='gauntlet.gauntletrun')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='gauntletrun',
            index=models.Index(fields=['user', 'status'], name='gauntlet_ga_user_id_020952_idx'),
        ),
        migrations.AddIndex(
            model_name='gauntletrun',
            index=models.Index(fields=['score'], name='gauntlet_ga_score_f70c51_idx'),
        ),
        migrations.AddIndex(
            model_name='gauntletrun',
            index=models.Index(fields=['-created_at'], name='gauntlet_ga_created_ab6062_idx'),
        ),
    ]
