# Generated by Django 6.0 on 2025-12-27 12:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0002_characteritem'),
        ('combat', '0003_combatlog'),
        ('encounters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], default='preparing', max_length=20)),
                ('current_encounter_index', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_encounters', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('short_rests_used', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('long_rests_used', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('long_rests_available', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_hp', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('max_hp', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('hit_dice_remaining', models.JSONField(default=dict)),
                ('spell_slots', models.JSONField(default=dict)),
                ('is_alive', models.BooleanField(default=True)),
                ('died_in_encounter', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_characters', to='campaigns.campaign')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_participations', to='characters.character')),
            ],
            options={
                'unique_together': {('campaign', 'character')},
            },
        ),
        migrations.CreateModel(
            name='CampaignEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encounter_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('rewards', models.JSONField(default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_encounters', to='campaigns.campaign')),
                ('combat_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_encounters', to='combat.combatsession')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_encounters', to='encounters.encounter')),
            ],
            options={
                'ordering': ['encounter_number'],
                'unique_together': {('campaign', 'encounter_number')},
            },
        ),
    ]
