# Generated by Django 6.0 on 2025-12-27 14:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='starting_level',
            field=models.IntegerField(choices=[(1, 'Level 1'), (3, 'Level 3'), (5, 'Level 5')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.CreateModel(
            name='CharacterXP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_xp', models.IntegerField(default=0)),
                ('total_xp_gained', models.IntegerField(default=0)),
                ('level_ups_gained', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xp_tracking', to='campaigns.campaigncharacter')),
            ],
        ),
        migrations.CreateModel(
            name='TreasureRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encounter_number', models.IntegerField()),
                ('room_type', models.CharField(choices=[('equipment', 'Equipment Room'), ('consumables', 'Consumables Room'), ('gold', 'Gold Room'), ('magical', 'Magic Item Room'), ('mystery', 'Mystery Room')], max_length=20)),
                ('discovered', models.BooleanField(default=False)),
                ('loot_distributed', models.BooleanField(default=False)),
                ('rewards', models.JSONField(default=dict)),
                ('discovered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasure_rooms', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['encounter_number'],
                'unique_together': {('campaign', 'encounter_number')},
            },
        ),
    ]
