# Generated by Django 6.0 on 2025-12-27 14:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_starting_level_characterxp_treasureroom'),
        ('characters', '0003_character_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='start_mode',
            field=models.CharField(choices=[('solo', 'Solo - Start alone, recruit during run'), ('party', 'Party - Start with selected characters')], default='party', help_text='Solo mode: Start with 1 character, can recruit up to 3 more. Party mode: Start with selected characters, no recruitment.', max_length=10),
        ),
        migrations.AddField(
            model_name='campaign',
            name='starting_party_size',
            field=models.IntegerField(default=1, help_text='Starting party size (1-4 characters). In solo mode, this is set to 1. In party mode, this is the number of characters added.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.CreateModel(
            name='RecruitableCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('personality_trait', models.TextField(blank=True, help_text='Personality trait or flavor text')),
                ('recruitment_description', models.TextField(help_text='Description shown when this recruit is available')),
                ('starting_stats', models.JSONField(blank=True, default=dict)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('starting_equipment', models.JSONField(blank=True, default=list, help_text='List of item IDs to give this recruit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.characterbackground')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characters.characterclass')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characters.characterrace')),
            ],
            options={
                'ordering': ['rarity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encounter_number', models.IntegerField(help_text='After which encounter this recruitment room appears')),
                ('discovered', models.BooleanField(default=False)),
                ('discovered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available_recruits', models.ManyToManyField(related_name='recruitment_rooms', to='campaigns.recruitablecharacter')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_rooms', to='campaigns.campaign')),
                ('recruit_selected', models.ForeignKey(blank=True, help_text='The campaign character that was recruited from this room', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_source', to='campaigns.campaigncharacter')),
            ],
            options={
                'ordering': ['encounter_number'],
                'unique_together': {('campaign', 'encounter_number')},
            },
        ),
    ]
