# Generated by Django 6.0 on 2025-12-27 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_start_mode_campaign_starting_party_size_and_more'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasureRoomReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('gold_amount', models.IntegerField(default=0)),
                ('xp_bonus', models.IntegerField(default=0)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_rewards', to='campaigns.campaigncharacter')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('treasure_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_items', to='campaigns.treasureroom')),
            ],
            options={
                'ordering': ['-gold_amount', 'item'],
            },
        ),
    ]
