# Generated by Django 6.0 on 2025-12-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_treasureroomreward'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterxp',
            name='pending_asi_levels',
            field=models.JSONField(default=list, help_text='List of levels where ASI is pending player choice'),
        ),
        migrations.AddField(
            model_name='characterxp',
            name='pending_subclass_selection',
            field=models.BooleanField(default=False, help_text='True if character needs to select subclass'),
        ),
    ]
