# Generated by Django 5.0.2 on 2026-01-12 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_characterxp_pending_asi_levels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncharacter',
            name='gold',
            field=models.IntegerField(default=0, help_text='Gold pieces (GP)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
