# Generated by Django 5.0.2 on 2026-01-15 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_campaign_camp_user_status_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='biome',
            field=models.CharField(blank=True, choices=[('forest', 'Forest'), ('desert', 'Desert'), ('mountain', 'Mountain'), ('swamp', 'Swamp'), ('plains', 'Plains'), ('underdark', 'Underdark'), ('urban', 'Urban'), ('arctic', 'Arctic')], help_text='Primary biome for this gauntlet', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='default_encounter_count',
            field=models.IntegerField(default=5, help_text='Number of regular encounters before boss (default 5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AddField(
            model_name='campaignencounter',
            name='boss_loot_table',
            field=models.JSONField(blank=True, default=dict, help_text='Special boss loot (guaranteed items, gold bonus, XP multiplier)'),
        ),
        migrations.AddField(
            model_name='campaignencounter',
            name='is_boss',
            field=models.BooleanField(default=False, help_text='True if this is a boss encounter'),
        ),
    ]
